[meta]
name = "ASR_6"
pretrained_path = "D:\\MARONE\\WOLOF\\SPEECH_TO_TEXT\\MODELS\\PRETRAINED_WAV2VEC\\WAV2VEC2_PRETRAINED_NEW_\\checkpoints\\saved_model_epoch_2"
seed = 19
epochs = 50
save_dir = "MODELS\\WAV2VEC2"
gradient_accumulation_steps = 8
use_amp = true
device_ids = "0,1"
sr = 16000
max_clip_grad_norm = 5.0

[special_tokens]
bos_token = "<bos>"
eos_token = "<eos>"
unk_token = "<unk>"
pad_token = "<pad>"

[huggingface]
push_to_hub = false
push_every_validation_step = false
overwrite_output_dir = false
blocking = false

[train_dataset]
path = "base.base_dataset.BaseDataset"

[val_dataset]
path = "base.base_dataset.BaseDataset"

[optimizer]
lr = 1e-6

[scheduler]
max_lr = 5e-5

[trainer]
path = "trainer.trainer.Trainer"

[huggingface.args]
local_dir = "D:\\MARONE\\WOLOF\\SPEECH_TO_TEXT\\MODELS\\WAV2VEC2\\ASR_6\\huggingface-hub"
use_auth_token = true
clone_from = ""

[train_dataset.args]
path = "D:\\MARONE\\WOLOF\\SPEECH_TO_TEXT\\DATA\\CLEANED\\WOLOF_AUDIO_TRANS\\train_data.csv"
preload_data = false
delimiter = "|"
nb_workers = 16

[train_dataset.dataloader]
batch_size = 5
num_workers = 16
pin_memory = true
drop_last = true

[train_dataset.sampler]
shuffle = true
drop_last = true

[val_dataset.args]
path = "D:\\MARONE\\WOLOF\\SPEECH_TO_TEXT\\DATA\\CLEANED\\WOLOF_AUDIO_TRANS\\validation_data.csv"
preload_data = false
delimiter = "|"
nb_workers = 16

[val_dataset.dataloader]
batch_size = 1
num_workers = 4

[val_dataset.sampler]
shuffle = false
drop_last = false

[trainer.args]
validation_interval = 1000
save_max_metric_score = false
